// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47sxBSPmYFbBfSHL_8kAV8gLXyaaAqcI',
    appId: '1:817595942719:web:277bbaba813d37676e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    authDomain: 'foodin-93814.firebaseapp.com',
    storageBucket: 'foodin-93814.appspot.com',
    measurementId: 'G-D28YHW8HVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIWF9UdhrVJZirlgh_WP5_Fk-J36qM7Y',
    appId: '1:817595942719:android:9997001d93326fd96e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    storageBucket: 'foodin-93814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBhhKTZSUdQCRh22gIySE5uYl9C9voYY',
    appId: '1:817595942719:ios:ffdb5e6b6c6f22016e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    storageBucket: 'foodin-93814.appspot.com',
    androidClientId: '817595942719-f9164i8868kmv29m16807uc7pf750fcp.apps.googleusercontent.com',
    iosClientId: '817595942719-t1r19uljo174nh3i5egtks3148es0r0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodinz',
  );
}
